// Gerado automaticamente por excel_para_json.py
// NÃO editar à mão.
window.BANCO_DADOS = {
  "msf": [
    {
      "nome": [
        "Paracetamol",
        "Acetaminofeno"
      ],
      "condicao": "Dor e Febre",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": ";50",
      "dose": "",
      "concentracao": "500 mg/5 ml|100",
      "intervalo": "6",
      "formula": "{#p*15/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (15 minutos).#Não exceder 4 g por dia em adultos.#Não exceder 60 mg/kg/dia em crianças.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": [
        "Paracetamol",
        "Acetaminofeno"
      ],
      "condicao": "Dor e Febre",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "50;",
      "dose": "",
      "concentracao": "500 mg/5 ml|100",
      "intervalo": "6",
      "formula": "{1000/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (15 minutos).#Não exceder 4 g por dia em adultos.#Não exceder 60 mg/kg/dia em crianças.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Ceftriaxona",
      "condicao": "Infeções Graves",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": ";50",
      "dose": "50,80,50,mg/kg",
      "concentracao": "1 g/10 ml|100",
      "intervalo": "24",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "#[1] Dissolver o pó em 10 ml de água para injeção. Administrar por IV lenta (2-4 minutos) ou IM profunda.#Não administrar com soluções contendo cálcio (precipitação).#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Ceftriaxona",
      "condicao": "Infeções Graves",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "50;",
      "dose": "1,2,1,g",
      "concentracao": "1 g/10 ml|100",
      "intervalo": "24",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Dissolver o pó em 10 ml de água para injeção. Administrar por IV lenta (2-4 minutos) ou IM profunda.#Não administrar com soluções contendo cálcio (precipitação).#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Metronidazol",
      "condicao": "Infeções Anaeróbias",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "500 mg/100 ml|5",
      "intervalo": "8",
      "formula": "{#p*7.5/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por perfusão IV (20-30 minutos).#Reduzir dose em insuficiência hepática grave.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Metronidazol",
      "condicao": "Infeções Anaeróbias",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "500 mg/100 ml|5",
      "intervalo": "8",
      "formula": "{500/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por perfusão IV (20-30 minutos).#Reduzir dose em insuficiência hepática grave.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Gentamicina",
      "condicao": "Infeções por Gram-Negativos",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "5,7.5,5,mg/kg",
      "concentracao": "80 mg/2 ml|40",
      "intervalo": "24",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (3-5 minutos) ou IM.#Monitorizar função renal e auditiva.#Evitar uso prolongado (risco de nefrotoxicidade e ototoxicidade).#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Gentamicina",
      "condicao": "Infeções por Gram-Negativos",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "5,7,5,mg/kg",
      "concentracao": "80 mg/2 ml|40",
      "intervalo": "24",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (3-5 minutos) ou IM.#Monitorizar função renal e auditiva.#Evitar uso prolongado (risco de nefrotoxicidade e ototoxicidade).#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Dexametasona",
      "condicao": "Reações Alérgicas Graves",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "4 mg/1 ml|4",
      "intervalo": "6",
      "formula": "{#p*0.15/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta ou IM.#Usar com precaução em doentes diabéticos ou com infeções ativas.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Dexametasona",
      "condicao": "Reações Alérgicas Graves",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "4,8,4,mg",
      "concentracao": "4 mg/1 ml|4",
      "intervalo": "6",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta ou IM.#Usar com precaução em doentes diabéticos ou com infeções ativas.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Furosemida",
      "condicao": "Edema Agudo do Pulmão",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "20,40,20,mg",
      "concentracao": "20 mg/2 ml|10",
      "intervalo": "2",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (1-2 minutos).#Monitorizar eletrólitos e função renal.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Furosemida",
      "condicao": "Edema Agudo do Pulmão",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "0.5,1,0.5,mg/kg",
      "concentracao": "20 mg/2 ml|10",
      "intervalo": "8",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (1-2 minutos).#Monitorizar eletrólitos e função renal.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Hidrocortisona",
      "condicao": "Insuficiência Adrenal Aguda",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "100 mg/2 ml|50",
      "intervalo": "6",
      "formula": "{100/#c} ml",
      "adicionais": "#[1] Dissolver o pó em 2 ml de água para injeção. Administrar por IV lenta ou IM.#Em crise adrenal, administrar imediatamente.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Hidrocortisona",
      "condicao": "Insuficiência Adrenal Aguda",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "100 mg/2 ml|50",
      "intervalo": "6",
      "formula": "{#p*2/#c} ml",
      "adicionais": "#[1] Dissolver o pó em 2 ml de água para injeção. Administrar por IV lenta ou IM.#Em crise adrenal, administrar imediatamente.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Morfina",
      "condicao": "Dor Intensa",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "2,10,2,mg",
      "concentracao": "10 mg/1 ml|10",
      "intervalo": "4",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (3-5 minutos) ou IM/SC.#Monitorizar frequência respiratória.#Ter naloxona disponível para reversão.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Morfina",
      "condicao": "Dor Intensa",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "0.05,0.1,0.05,mg/kg",
      "concentracao": "10 mg/1 ml|10",
      "intervalo": "4",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta (3-5 minutos) ou IM/SC.#Monitorizar frequência respiratória.#Ter naloxona disponível para reversão.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Midazolam",
      "condicao": "Sedação",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "1,2.5,1,mg",
      "concentracao": "5 mg/1 ml|5",
      "intervalo": "24*",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta ou IM.#Monitorizar frequência respiratória e saturação de oxigénio.#Ter flumazenil disponível para reversão.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": "Midazolam",
      "condicao": "Sedação",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "0.05,0.1,0.05,mg/kg",
      "concentracao": "5 mg/1 ml|5",
      "intervalo": "24*",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta ou IM.#Monitorizar frequência respiratória e saturação de oxigénio.#Ter flumazenil disponível para reversão.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": [
        "Adrenalina",
        "Epinefrina"
      ],
      "condicao": "Anafilaxia",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "1 mg/1 ml|1",
      "intervalo": "24*",
      "formula": "{0.5/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta ou IM (anafilaxia).#Em anafilaxia, administrar IM na face anterolateral da coxa.#Repetir a cada 5-15 minutos se necessário.#",
      "notas": "MSF Essential Drugs Guidelines."
    },
    {
      "nome": [
        "Adrenalina",
        "Epinefrina"
      ],
      "condicao": "Anafilaxia",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "",
      "dose": "",
      "concentracao": "1 mg/1 ml|1",
      "intervalo": "24*",
      "formula": "{#p*0.01/#c} ml",
      "adicionais": "#[1] Solução pronta a usar. Administrar por IV lenta ou IM (anafilaxia).#Em anafilaxia, administrar IM na face anterolateral da coxa.#Repetir a cada 5-15 minutos se necessário.#",
      "notas": "MSF Essential Drugs Guidelines."
    }
  ],
  "molde": []
};
